### ISSUE TITLE
I need help to set this up

### ISSUE THREAD

**Issue by pijn-tech** [terorie/discord-influx#7]

**Comment by pijn-tech** [comment]
How can I update? 
Try to contact me the sooner. Thanks I hpe someone to help me.
What do you mean with "replace guild-name with the persistent name in Influx and..."
Where is the "persistent name in Influx"?

**Comment by riptl** [comment]
@pijn-tech First of all your bot token is still clearly visible in the screenshot, you might want to remove the screenshot so no one steals your token. You can also just copy-paste the command line output directly as text (EDIT: and remove your token).

The error shown in your screenshot means that the API has rejected your request because of insufficient authorization. Verify the following things:
* Assuming you are using a bot token, check you have set `DISCORD_TOKEN="Bot XXXXXX"` (notice the `Bot` in the beginning. I do not see that in your screenshot).
* Your bot token has permissions integer 65536.

> What do you mean with "replace guild-name with the persistent name in Influx and..."
Where is the "persistent name in Influx"?

The parameter `guild-name` is the name that your guild gets in the Influx database. It will also show up in the Grafana drop-down. Just call it `guild` if you don't know what to specify.

Let me know when you get it to work.

**Comment by pijn-tech** [comment]
Thankss I will try now
Do you have discord? I called princejn#9910

1.Where DISCORD_TOKEN="Bot XXXXXX"? I don't exactly what I need to type.

**I try this following options.**

export DISCORD_TOKEN='xxxx'; ./discord-influx 'lpxw`/7xxxxx -s 0

export DISCORD_TOKEN='Bot xxxx'; ./discord-influx 'lpxw`/7xxxxx -s 0

export Discord token local storage token or bot token?="Bot name?" "integer 65536?")'; ./discord-influx 'lpxw`/7xxxxx -s 0

I try this like last option.

export **Discord token local storage token**=**Bot name bot token**'; ./discord-influx 'lpxw`/7xxxxx -s 0

![1](https://user-images.githubusercontent.com/51449054/87734734-c4ae3700-c7d3-11ea-8e3c-ee8cae017987.PNG)

**Comment by riptl** [comment]
@pijn-tech I don't have Discord at the moment. Let's just go over the steps required:

1. Set your bot up with permissions integer 65536, in the Discord developers portal.

![image](https://user-images.githubusercontent.com/21371810/87802499-9cfdb400-c851-11ea-90ca-acf82fcfdc17.png)

2. Set your token.

Replace `xxx` with the token it shows you in the bot tab under "CLIENT SECRET".

```shell
export DISCORD_TOKEN='Bot xxxx'
```

3. Set up the app the first time. Only run this step once, this will take a while.

Replace `77777777` with the guild ID (for example, 482467812179181568)

```shell
./discord-influx LPXW/77777777 -s 0
```

4. Then, have it run in the backgoround.

```shell
./discord-influx LPXW/77777777
```
